services:
  - type: web
    name: btc-donation-site
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    region: oregon
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
